require:
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - terracop.gemspec

Style/AsciiComments:
  # I will use emojis!
  Enabled: false

RSpec/NestedGroups:
  Max: 7

Style/GuardClause:
  # Usually good, sometimes dumb.
  Enabled: false

RSpec/SubjectStub:
  # Sometimes, there's no other way.
  Enabled: false
