require:
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - terracop.gemspec

Style/AsciiComments:
  # I will use emojis!
  Enabled: false

RSpec/NestedGroups:
  Max: 7

# Usually good, sometimes dumb.
Style/GuardClause:
  Enabled: false
